=== FlorentinTh/LE2ML-Misc/configuration/conf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LIARA Configuration Schema",
  "description": "JSON schema to validate configuration files of ML pipelines.",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "pipeline": {
      "type": "string",
      "enum": ["machine_learning", "deep_learning"]
    },
    "source": {
      "type": "string"
    },
    "process": {
      "type": "string",
      "enum": ["train", "test", "none"]
    },
    "model": {
      "type": "string",
      "format": "iri-reference"
    },
    "input": {
      "type": "object",
      "properties": {
        "file": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["raw", "features"]
            },
            "filename": {
              "type": "string",
              "format": "uri-reference"
            }
          },
          "additionalProperties": false,
          "required": ["type", "filename"]
        },
        "ws": {
          "type": "string",
          "format": "uri-reference"
        }
      },
      "additionalProperties": false,
      "anyOf": [
        {
          "required": ["file"]
        },
        {
          "required": ["ws"]
        }
      ],
      "not": {
        "required": ["file", "ws"]
      }
    },
    "windowing": {
      "oneOf": [
        {
          "properties": {
            "enable": {
              "const": false
            }
          },
          "additionalProperties": false
        },
        {
          "properties": {
            "enable": {
              "const": true
            },
            "parameters": {
              "type": "object",
              "properties": {
                "length": {
                  "type": "integer",
                  "minimum": 0
                },
                "function": {
                  "type": "object",
                  "properties": {
                    "label": {
                      "type": "string",
                      "enum": ["none", "rectangular", "triangular", "hamming", "hann"]
                    },
                    "container": {
                      "type": "string",
                      "pattern": "^[a-z0-9-]+$",
                      "minLength": 1
                    }
                  },
                  "additionalProperties": false,
                  "required": ["label", "container"],
                  "allOf": [
                    {
                      "if": {
                        "properties": {
                          "label": {
                            "enum": ["rectangular", "triangular", "hamming", "hann"]
                          }
                        }
                      },
                      "then": {
                        "required": ["container"]
                      }
                    }
                  ]
                },
                "overlap": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 100
                }
              },
              "additionalProperties": false,
              "required": ["length", "function", "overlap"]
            }
          },
          "additionalProperties": false,
          "required": ["parameters"]
        }
      ]
    },
    "features": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "pattern": "^[a-z0-9_]+$",
            "minLength": 1
          },
          "container": {
            "type": "string",
            "pattern": "^[a-z0-9-]+$",
            "minLength": 1
          }
        },
        "additionalProperties": false,
        "required": ["label", "container"]
      },
      "uniqueItems": true
    },
    "algorithm": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-z0-9_]+$",
          "minLength": 1
        },
        "container": {
          "type": "string",
          "pattern": "^[a-z0-9-]+$",
          "minLength": 1
        },
        "parameters": {
          "type": "object"
        }
      },
      "additionalProperties": false,
      "required": ["name", "container", "parameters"]
    }
  },
  "required": ["version", "pipeline", "source", "process", "input", "windowing"],
  "allOf": [
    {
      "if": {
        "properties": {
          "process": {
            "enum": ["train", "test"]
          }
        }
      },
      "then": {
        "required": ["model"]
      },
      "else": {
        "not": {
          "required": ["model"]
        }
      }
    },
    {
      "if": {
        "properties": {
          "process": {
            "enum": ["train", "test"]
          }
        }
      },
      "then": {
        "required": ["algorithm"]
      }
    }
  ]
}

=== FlorentinTh/LE2ML-Misc/configuration/examples/train.conf.json
{
  "version": "1",
  "pipeline": "machine_learning",
  "source": "inertial",
  "process": "train",
  "model": "./path/to/model.ext",
  "input": {
    "file": {
      "type": "raw",
      "filename": "./path/to/file.ext"
    }
  },
  "windowing": {
    "enable": true,
    "parameters": {
      "length": 60,
      "function": {
        "label": "none",
        "container": "core-window-functions"
      },
      "overlap": 0
    }
  },
  "features": [
    {
      "label": "average",
      "container": "core-features"
    },
    {
      "label": "std_dev",
      "container": "core-features"
    }
  ],
  "algorithm": {
    "name": "random_forest",
    "container": "core-py-sk",
    "parameters": {
      "example": "parameter"
    }
  }
}
